arch:
  - amd64
os: linux
dist: jammy

language: bash

services:
  - docker

before_install:
  - mkdir -vp ~/.docker/cli-plugins/
  - curl --silent -L "https://github.com/docker/buildx/releases/download/v0.23.0/buildx-v0.23.0.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
  - chmod a+x ~/.docker/cli-plugins/docker-buildx
  
script:
  - docker login -u="moussavdb" --password-stdin <<< "$DOCKER_PASSWORD";
  - docker buildx create --use
  - docker buildx build --push --platform linux/arm64/v8 --tag moussavdb/service-glpi:10.0.18 .
